name: Go

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "1 0 * * *"

jobs:

  build:
    name: Run
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Spread the word
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: make ineedtoknow
